### ISSUE TITLE
The Huggingface Demo seems to have an error.

### ISSUE THREAD

**Issue by ninjasaid2k** [SHI-Labs/Prompt-Free-Diffusion#1]
```
Runtime error
0:02, 104MB/s]
Downloading (…)ime-v1-0.safetensors:  83%|████████▎ | 986M/1.18G [00:09<00:01, 103MB/s]
Downloading (…)ime-v1-0.safetensors:  85%|████████▌ | 1.01G/1.18G [00:10<00:01, 104MB/s]
Downloading (…)ime-v1-0.safetensors:  87%|████████▋ | 1.03G/1.18G [00:10<00:01, 92.6MB/s]
Downloading (…)ime-v1-0.safetensors:  89%|████████▉ | 1.05G/1.18G [00:10<00:01, 86.4MB/s]
Downloading (…)ime-v1-0.safetensors:  91%|█████████▏| 1.08G/1.18G [00:10<00:01, 97.4MB/s]
Downloading (…)ime-v1-0.safetensors:  93%|█████████▎| 1.10G/1.18G [00:11<00:00, 103MB/s] 
Downloading (…)ime-v1-0.safetensors:  96%|█████████▌| 1.13G/1.18G [00:11<00:00, 107MB/s]
Downloading (…)ime-v1-0.safetensors:  98%|█████████▊| 1.15G/1.18G [00:11<00:00, 105MB/s]
Downloading (…)ime-v1-0.safetensors:  99%|█████████▉| 1.17G/1.18G [00:11<00:00, 117MB/s]
Downloading (…)ime-v1-0.safetensors: 100%|██████████| 1.18G/1.18G [00:11<00:00, 99.1MB/s]
Traceback (most recent call last):
  File "/home/user/app/app.py", line 312, in <module>
    pfd_inference = prompt_free_diffusion(
  File "/home/user/app/app.py", line 146, in __init__
    self.net = get_model()(cfgm)
  File "/home/user/app/lib/model_zoo/common/get_model.py", line 88, in __call__
    net = self.model[t](**args)
  File "/home/user/app/lib/model_zoo/pfd.py", line 461, in __init__
    super().__init__(*args, **kwargs)
  File "/home/user/app/lib/model_zoo/pfd.py", line 60, in __init__
    highlight_print("Running in {} mode".format(self.parameterization))
  File "/home/user/app/lib/model_zoo/pfd.py", line 22, in highlight_print
    print_log('')
  File "/home/user/app/lib/log_service.py", line 14, in print_log
    grank, lrank, _ = sync.get_rank('all')
  File "/home/user/app/lib/sync.py", line 40, in get_rank
    global_rank % local_world_size, \
ZeroDivisionError: integer division or modulo by zero
```

**Comment by xingqian2018** [comment]
Now the demo is up
