### ISSUE TITLE
Install broken both on Windows and Linux

### ISSUE THREAD

**Issue by maepopi** [SHI-Labs/Prompt-Free-Diffusion#28]
Hello!

I've been trying for hours to install the repo, both on Linux and Windows, but I keep encountering problems. 

Ok so the first problem comes when I try to install the requirements. There, when it's time to download pyyaml, I have this error:

```
Downloading PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\maely\.conda\envs\seecoders\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\maely\.conda\envs\seecoders\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\maely\.conda\envs\seecoders\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\__init__.py", line 111, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
          return run_commands(dist)
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
          dist.run_commands()
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\dist.py", line 948, in run_command
          super().run_command(command)
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 983, in run_command
          cmd_obj.run()
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 311, in run
          self.find_sources()
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 319, in find_sources
          mm.run()
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 540, in run
          self.add_defaults()
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\command\sdist.py", line 105, in add_defaults
          super().add_defaults()
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "C:\Users\maely\AppData\Local\Temp\pip-build-env-r75gv1gy\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
```

I tried changing the requirements to Pyyaml 5.3.1, same error. I deleted any mention of a version to let it install any version of Pyyaml. But then, it's matplotlib that throws an error:

```
UPDATING build\lib.win-amd64-cpython-310\matplotlib\_version.py
      set build\lib.win-amd64-cpython-310\matplotlib\_version.py to '3.4.2'
      running build_ext
      Extracting /project/freetype/freetype2/2.6.1/freetype-2.6.1.tar.gz
      Building freetype in build\freetype-2.6.1
      msbuild build\freetype-2.6.1\builds\windows\vc2010\freetype.sln /t:Clean;Build /p:Configuration=Release;Platform=x64
      error: command 'msbuild' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for matplotlib
  Running setup.py clean for matplotlib
Failed to build matplotlib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (matplotlib)
```

Same thing, I update the requirements to bypass the specific version. At this point I can tell it's not going to work, but I try anyway. The installation finishes fine, I download all the models that I put into the "pretrained" folder, but when I launch the app, I'm stuck with this new message 

```
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Load model from [pretrained/pfd/vae/sd-v2-0-base-autokl.pth] strict [True].
Traceback (most recent call last):
  File "F:\AI_HUB\Prompt-Free-Diffusion\app.py", line 277, in <module>
    pfd_inference = prompt_free_diffusion(
  File "F:\AI_HUB\Prompt-Free-Diffusion\app.py", line 111, in __init__
    self.net = get_model()(cfgm)
  File "F:\AI_HUB\Prompt-Free-Diffusion\lib\model_zoo\common\get_model.py", line 88, in __call__
    net = self.model[t](**args)
  File "F:\AI_HUB\Prompt-Free-Diffusion\lib\model_zoo\pfd.py", line 461, in __init__
    super().__init__(*args, **kwargs)
  File "F:\AI_HUB\Prompt-Free-Diffusion\lib\model_zoo\pfd.py", line 62, in __init__
    self.vae = self.get_model_list(vae_cfg_list)
  File "F:\AI_HUB\Prompt-Free-Diffusion\lib\model_zoo\pfd.py", line 107, in get_model_list
    net[name] = get_model()(cfg)
  File "F:\AI_HUB\Prompt-Free-Diffusion\lib\model_zoo\common\get_model.py", line 117, in __call__
    get_total_param_sum(net) ))
  File "F:\AI_HUB\Prompt-Free-Diffusion\lib\model_zoo\common\utils.py", line 291, in get_total_param_sum
    s = sum(p.cpu().detach().numpy().sum().item() for p in net.parameters())
  File "F:\AI_HUB\Prompt-Free-Diffusion\lib\model_zoo\common\utils.py", line 291, in <genexpr>
    s = sum(p.cpu().detach().numpy().sum().item() for p in net.parameters())
RuntimeError: Numpy is not available
```

I've tried everything, from reinstalling numpy to reinstalling the whole stuff again, but nothing works. In desperation, I've tried the plugin that was made for A111, but the results are really bad and extremely far from the results shown in the paper, so I was really hoping to make the actual repo work without any intermediary.

Does anyone encounter the same problems?

**Comment by maepopi** [comment]
OK I think I've succeeded in installing it on Windows by making the conda environment Python 3.9 and NOT 3.10
The app has started and is loading the samplers, standing by...
