### ISSUE TITLE
Error when loading seecoder : Error(s) in loading state_dict for PromptFreeDiffusion_with_control: Missing key(s) in state_dict:

### ISSUE THREAD

**Issue by Yaiol** [SHI-Labs/Prompt-Free-Diffusion#9]
Conda 23.3.1
Python 3.10.11

Load context encoder from [pretrained/pfd/seecoder/seecoder-v1-0.safetensors] strict [True].
Traceback (most recent call last):
  File "D:\Apps\sd\pfd-webui\app.py", line 294, in <module>
    pfd_inference = prompt_free_diffusion(
  File "D:\Apps\sd\pfd-webui\app.py", line 131, in __init__
    self.action_load_diffuser(tag_diffuser)
  File "D:\Apps\sd\pfd-webui\app.py", line 203, in action_load_diffuser
    self.load_diffuser(pretrained)
  File "D:\Apps\sd\pfd-webui\app.py", line 173, in load_diffuser
    self.net.load_state_dict(sd, strict=True)
  File "C:\Users\Yaiol\App\miniconda\envs\app-pfd\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PromptFreeDiffusion_with_control:
        Missing key(s) in state_dict: "diffuser.image.time_embed.0.weight", "diffuser.image.time_embed.0.bias", "diffuser.image.time_embed.2.weight", "diffuser.image.time_embed.2.bias", "diffuser.image.data_blocks.0.0.weight", "diffuser.image.data_blocks.0.0.bias", "diffuser.image.data_blocks.1.0.in_layers.0.weight", "diffuser.image.data_blocks.1.0.in_layers.0.bias", "diffuser.image.data_blocks.1.0.in_layers.2.weight", 
...
"model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm3.weight", "model.diffusion_model.time_embed.0.bias", "model.diffusion_model.time_embed.0.weight", "model.diffusion_model.time_embed.2.bias", "model.diffusion_model.time_embed.2.weight".

**Comment by Yaiol** [comment]
My mistake loading wrong model
